### PR TITLE
small unit test for deno check with watch arg

### PR DESCRIPTION
**Pull request by VishnuJin**
hey mate, 
just a small unit test for your change [15325](https://github.com/denoland/deno/pull/15325) , 

_I now don't have time for writing integration test but seems this is fine as of now at-least_

### CODE REVIEW

**Review by cuobiezi — COMMENTED** [review]
@VishnuJin Seem we should to remove it to check.rs.

**Comment by VishnuJin** [comment]
> @VishnuJin Seem we should to remove it to check.rs.

all flag related tests stays in `cli/args/flags.rs` so better leave it there,

**Comment by VishnuJin** [comment]
@cuobiezi 
I messed up this PR, you can simply copy paste the test code to your branch or cherry-pick my commit from https://github.com/VishnuJin/deno/tree/fix/unit-test-for-14858

**Comment by cuobiezi** [comment]
@VishnuJin Done. Thanks

**Pull request closed without merging**
